export const films = [
  {
    id: 0,
    name: "The Grand Budapest Hotel",
    poster_image: "img/the-grand-budapest-hotel-poster.jpg",
    preview_image: "img/the-grand-budapest-hotel-poster.jpg",
    background_image: "img/bg-the-grand-budapest-hotel.jpg",
    background_color: "#ffffff",
    video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    preview_video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    description: "In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave&apos;s friend and protege.",
    rating: 8.9,
    scores_count: 240,
    director: "Wes Andreson",
    starring: ["Bill Murray", "Edward Norton", "Jude Law", "Willem Dafoe", "Saoirse Ronan"],
    run_time: 99,
    genre: "Comedy",
    released: 2014,
    is_favorite: false
  },
  {
    id: 1,
    name: "Fantastic Beasts: The Crimes of Grindelwald",
    poster_image: "img/fantastic-beasts-the-crimes-of-grindelwald.jpg",
    preview_image: "img/fantastic-beasts-the-crimes-of-grindelwald.jpg",
    background_image: "img/fantastic-beasts-the-crimes-of-grindelwald.jpg",
    background_color: "#ffffff",
    video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    preview_video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    description: "In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave's friend and protege.",
    rating: 8.9,
    scores_count: 240,
    director: "Wes Andreson",
    starring: ["Bill Murray", "Edward Norton", "Jude Law", "Willem Dafoe", "Saoirse Ronan"],
    run_time: 125,
    genre: "Comedy",
    released: 2014,
    is_favorite: false
  },
  {
    id: 2,
    name: "Bohemian Rhapsody",
    poster_image: "img/bohemian-rhapsody.jpg",
    preview_image: "img/bohemian-rhapsody.jpg",
    background_image: "img/bohemian-rhapsody.jpg",
    background_color: "#ffffff",
    video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    preview_video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    description: "In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave's friend and protege.",
    rating: 8.9,
    scores_count: 240,
    director: "Wes Andreson",
    starring: ["Bill Murray", "Edward Norton", "Jude Law", "Willem Dafoe", "Saoirse Ronan"],
    run_time: 99,
    genre: "Comedy",
    released: 2014,
    is_favorite: false
  },
  {
    id: 3,
    name: "Macbeth",
    poster_image: "img/macbeth.jpg",
    preview_image: "img/macbeth.jpg",
    background_image: "img/macbeth.jpg",
    background_color: "#ffffff",
    video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    preview_video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    description: "In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave's friend and protege.",
    rating: 8.9,
    scores_count: 240,
    director: "Wes Andreson",
    starring: ["Bill Murray", "Edward Norton", "Jude Law", "Willem Dafoe", "Saoirse Ronan"],
    run_time: 99,
    genre: "Comedy",
    released: 2014,
    is_favorite: false
  },
  {
    id: 4,
    name: "Aviator",
    poster_image: "img/aviator.jpg",
    preview_image: "img/aviator.jpg",
    background_image: "img/aviator.jpg",
    background_color: "#ffffff",
    video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    preview_video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    description: "In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave's friend and protege.",
    rating: 8.9,
    scores_count: 240,
    director: "Wes Andreson",
    starring: ["Bill Murray", "Edward Norton", "Jude Law", "Willem Dafoe", "Saoirse Ronan"],
    run_time: 99,
    genre: "Comedy",
    released: 2014,
    is_favorite: false
  },
  {
    id: 5,
    name: "What We Do in the Shadows",
    poster_image: "img/what-we-do-in-the-shadows.jpg",
    preview_image: "img/what-we-do-in-the-shadows.jpg",
    background_image: "img/what-we-do-in-the-shadows.jpg",
    background_color: "#ffffff",
    video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    preview_video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    description: "In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave's friend and protege.",
    rating: 8.9,
    scores_count: 240,
    director: "Wes Andreson",
    starring: ["Bill Murray", "Edward Norton", "Jude Law", "Willem Dafoe", "Saoirse Ronan"],
    run_time: 99,
    genre: "Comedy",
    released: 2014,
    is_favorite: false
  },
  {
    id: 6,
    name: "We need to talk about Kevin",
    poster_image: "img/we-need-to-talk-about-kevin.jpg",
    preview_image: "img/we-need-to-talk-about-kevin.jpg",
    background_image: "img/we-need-to-talk-about-kevin.jpg",
    background_color: "#ffffff",
    video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    preview_video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    description: "In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave's friend and protege.",
    rating: 8.9,
    scores_count: 240,
    director: "Wes Andreson",
    starring: ["Bill Murray", "Edward Norton", "Jude Law", "Willem Dafoe", "Saoirse Ronan"],
    run_time: 99,
    genre: "Comedy",
    released: 2014,
    is_favorite: false
  },
  {
    id: 7,
    name: "Revenant",
    poster_image: "img/revenant.jpg",
    preview_image: "img/revenant.jpg",
    background_image: "img/revenant.jpg",
    background_color: "#ffffff",
    video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    preview_video_link: "https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4",
    description: "In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave's friend and protege.",
    rating: 8.9,
    scores_count: 240,
    director: "Wes Andreson",
    starring: ["Bill Murray", "Edward Norton", "Jude Law", "Willem Dafoe", "Saoirse Ronan"],
    run_time: 99,
    genre: "Comedy",
    released: 2014,
    is_favorite: false
  },
];
